name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [  20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn ci
    - run: yarn build
    - uses: actions/checkout@v3
    - name: Deploy to GitHub Pages
      uses: actions/deploy-gh-pages@v4  # Deploy using the official action
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # The branch configured in GitHub Pages settings
          folder: build  # The output directory after building (usually 'build')
